"""Add modern SQLAlchemy 2.x example models

Revision ID: 6f7e9b6ff1ab
Revises: 2e84d23d2884
Create Date: 2025-09-21 12:27:03.616937

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6f7e9b6ff1ab"
down_revision: Union[str, None] = "2e84d23d2884"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "modern_users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=True),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_modern_users_email"), "modern_users", ["email"], unique=True
    )
    op.create_index(op.f("ix_modern_users_id"), "modern_users", ["id"], unique=False)
    op.create_index(
        op.f("ix_modern_users_username"), "modern_users", ["username"], unique=True
    )
    op.create_table(
        "modern_posts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["modern_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_modern_posts_id"), "modern_posts", ["id"], unique=False)
    op.create_index(
        op.f("ix_modern_posts_title"), "modern_posts", ["title"], unique=False
    )
    op.create_index(op.f("ix_activity_logs_id"), "activity_logs", ["id"], unique=False)
    op.create_index(op.f("ix_audit_trails_id"), "audit_trails", ["id"], unique=False)
    op.drop_constraint(
        op.f("security_settings_user_id_key"), "security_settings", type_="unique"
    )
    op.create_index(
        op.f("ix_security_settings_id"), "security_settings", ["id"], unique=False
    )
    op.alter_column("users", "is_active", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column(
        "users",
        "is_verified",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column("users", "is_superuser", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column(
        "users",
        "failed_login_attempts",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "users",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "users",
        "failed_login_attempts",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column("users", "is_superuser", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column(
        "users",
        "is_verified",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    op.alter_column("users", "is_active", existing_type=sa.BOOLEAN(), nullable=True)
    op.drop_index(op.f("ix_security_settings_id"), table_name="security_settings")
    op.create_unique_constraint(
        op.f("security_settings_user_id_key"),
        "security_settings",
        ["user_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_index(op.f("ix_audit_trails_id"), table_name="audit_trails")
    op.drop_index(op.f("ix_activity_logs_id"), table_name="activity_logs")
    op.drop_index(op.f("ix_modern_posts_title"), table_name="modern_posts")
    op.drop_index(op.f("ix_modern_posts_id"), table_name="modern_posts")
    op.drop_table("modern_posts")
    op.drop_index(op.f("ix_modern_users_username"), table_name="modern_users")
    op.drop_index(op.f("ix_modern_users_id"), table_name="modern_users")
    op.drop_index(op.f("ix_modern_users_email"), table_name="modern_users")
    op.drop_table("modern_users")
    # ### end Alembic commands ###
