"""add_text_templates_table

Revision ID: 36a511a2fa73
Revises: bfa15e737e5e
Create Date: 2025-12-26 01:39:11.359926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36a511a2fa73'
down_revision: Union[str, None] = 'bfa15e737e5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('text_templates',
    sa.Column('user_id', sa.Integer(), nullable=True, comment='Owner user ID (null for system templates)'),
    sa.Column('company_id', sa.Integer(), nullable=True, comment='Company ID (null for personal templates)'),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('shortcut', sa.String(length=50), nullable=False, comment='Trigger shortcut (e.g., /approve, !thanks)'),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False, comment='System template (available to all users)'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('use_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_templates_company_category', 'text_templates', ['company_id', 'category'], unique=False)
    op.create_index('ix_templates_user_shortcut', 'text_templates', ['user_id', 'shortcut'], unique=False)
    op.create_index(op.f('ix_text_templates_category'), 'text_templates', ['category'], unique=False)
    op.create_index(op.f('ix_text_templates_company_id'), 'text_templates', ['company_id'], unique=False)
    op.create_index(op.f('ix_text_templates_id'), 'text_templates', ['id'], unique=False)
    op.create_index(op.f('ix_text_templates_is_active'), 'text_templates', ['is_active'], unique=False)
    op.create_index(op.f('ix_text_templates_shortcut'), 'text_templates', ['shortcut'], unique=False)
    op.create_index(op.f('ix_text_templates_user_id'), 'text_templates', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_text_templates_user_id'), table_name='text_templates')
    op.drop_index(op.f('ix_text_templates_shortcut'), table_name='text_templates')
    op.drop_index(op.f('ix_text_templates_is_active'), table_name='text_templates')
    op.drop_index(op.f('ix_text_templates_id'), table_name='text_templates')
    op.drop_index(op.f('ix_text_templates_company_id'), table_name='text_templates')
    op.drop_index(op.f('ix_text_templates_category'), table_name='text_templates')
    op.drop_index('ix_templates_user_shortcut', table_name='text_templates')
    op.drop_index('ix_templates_company_category', table_name='text_templates')
    op.drop_table('text_templates')
    # ### end Alembic commands ###
