"""add_inbox_items_table

Revision ID: 59eea8df6687
Revises: e16d187435a7
Create Date: 2025-12-26 01:04:16.136291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59eea8df6687'
down_revision: Union[str, None] = 'e16d187435a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inbox_items',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.Enum('MESSAGE', 'NOTIFICATION', 'ACTIVITY', 'MENTION', name='inboxitemtype'), nullable=False),
    sa.Column('reference_type', sa.String(length=100), nullable=False),
    sa.Column('reference_id', sa.Integer(), nullable=False),
    sa.Column('source_model', sa.String(length=100), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('preview', sa.String(length=500), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('is_starred', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'NORMAL', 'HIGH', 'URGENT', name='inboxpriority'), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inbox_items_id'), 'inbox_items', ['id'], unique=False)
    op.create_index(op.f('ix_inbox_items_is_archived'), 'inbox_items', ['is_archived'], unique=False)
    op.create_index(op.f('ix_inbox_items_is_read'), 'inbox_items', ['is_read'], unique=False)
    op.create_index(op.f('ix_inbox_items_is_starred'), 'inbox_items', ['is_starred'], unique=False)
    op.create_index(op.f('ix_inbox_items_item_type'), 'inbox_items', ['item_type'], unique=False)
    op.create_index(op.f('ix_inbox_items_user_id'), 'inbox_items', ['user_id'], unique=False)
    op.create_index('ix_inbox_reference', 'inbox_items', ['reference_type', 'reference_id'], unique=False)
    op.create_index('ix_inbox_user_archived', 'inbox_items', ['user_id', 'is_archived'], unique=False)
    op.create_index('ix_inbox_user_type', 'inbox_items', ['user_id', 'item_type'], unique=False)
    op.create_index('ix_inbox_user_unread', 'inbox_items', ['user_id', 'is_read'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_inbox_user_unread', table_name='inbox_items')
    op.drop_index('ix_inbox_user_type', table_name='inbox_items')
    op.drop_index('ix_inbox_user_archived', table_name='inbox_items')
    op.drop_index('ix_inbox_reference', table_name='inbox_items')
    op.drop_index(op.f('ix_inbox_items_user_id'), table_name='inbox_items')
    op.drop_index(op.f('ix_inbox_items_item_type'), table_name='inbox_items')
    op.drop_index(op.f('ix_inbox_items_is_starred'), table_name='inbox_items')
    op.drop_index(op.f('ix_inbox_items_is_read'), table_name='inbox_items')
    op.drop_index(op.f('ix_inbox_items_is_archived'), table_name='inbox_items')
    op.drop_index(op.f('ix_inbox_items_id'), table_name='inbox_items')
    op.drop_table('inbox_items')
    # ### end Alembic commands ###
