"""Add activity_logs and messages tables

Revision ID: 6513586ffd9b
Revises: 4f8bf3d9988b
Create Date: 2025-12-25 15:18:14.009951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6513586ffd9b'
down_revision: Union[str, None] = '4f8bf3d9988b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=True),
    sa.Column('correlation_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('category', sa.Enum('AUTHENTICATION', 'AUTHORIZATION', 'USER_MANAGEMENT', 'DATA_MANAGEMENT', 'SYSTEM_MANAGEMENT', 'SECURITY', 'WORKFLOW', 'API', 'FILE_MANAGEMENT', 'CONFIGURATION', 'NOTIFICATION', 'INTEGRATION', name='activitycategory'), nullable=False),
    sa.Column('level', sa.Enum('DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL', name='activitylevel'), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('entity_name', sa.String(length=255), nullable=True),
    sa.Column('old_values', sa.Text(), nullable=True),
    sa.Column('new_values', sa.Text(), nullable=True),
    sa.Column('changed_fields', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('extra_data', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('request_method', sa.String(length=10), nullable=True),
    sa.Column('request_path', sa.String(length=500), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('response_time_ms', sa.Float(), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('is_suspicious', sa.Boolean(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_logs_action'), 'activity_logs', ['action'], unique=False)
    op.create_index(op.f('ix_activity_logs_category'), 'activity_logs', ['category'], unique=False)
    op.create_index('ix_activity_logs_company_date', 'activity_logs', ['company_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_activity_logs_company_id'), 'activity_logs', ['company_id'], unique=False)
    op.create_index(op.f('ix_activity_logs_correlation_id'), 'activity_logs', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_activity_logs_created_at'), 'activity_logs', ['created_at'], unique=False)
    op.create_index('ix_activity_logs_entity', 'activity_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_activity_logs_entity_id'), 'activity_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_activity_logs_entity_type'), 'activity_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_activity_logs_event_id'), 'activity_logs', ['event_id'], unique=True)
    op.create_index(op.f('ix_activity_logs_id'), 'activity_logs', ['id'], unique=False)
    op.create_index(op.f('ix_activity_logs_level'), 'activity_logs', ['level'], unique=False)
    op.create_index(op.f('ix_activity_logs_request_id'), 'activity_logs', ['request_id'], unique=False)
    op.create_index('ix_activity_logs_security', 'activity_logs', ['is_suspicious', 'risk_score'], unique=False)
    op.create_index(op.f('ix_activity_logs_session_id'), 'activity_logs', ['session_id'], unique=False)
    op.create_index('ix_activity_logs_user_action', 'activity_logs', ['user_id', 'action'], unique=False)
    op.create_index(op.f('ix_activity_logs_user_id'), 'activity_logs', ['user_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('message_type', sa.Enum('COMMENT', 'NOTE', 'SYSTEM', 'NOTIFICATION', 'EMAIL', 'LOG', 'APPROVAL', 'REJECTION', 'ASSIGNMENT', name='messagetype'), nullable=False),
    sa.Column('level', sa.Enum('INFO', 'SUCCESS', 'WARNING', 'ERROR', 'DEBUG', name='messagelevel'), nullable=False),
    sa.Column('attachments', sa.Text(), nullable=True),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('extra_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_index(op.f('ix_messages_message_type'), 'messages', ['message_type'], unique=False)
    op.create_index(op.f('ix_messages_model_name'), 'messages', ['model_name'], unique=False)
    op.create_index('ix_messages_model_record', 'messages', ['model_name', 'record_id'], unique=False)
    op.create_index(op.f('ix_messages_parent_id'), 'messages', ['parent_id'], unique=False)
    op.create_index(op.f('ix_messages_record_id'), 'messages', ['record_id'], unique=False)
    op.create_index('ix_messages_thread', 'messages', ['model_name', 'record_id', 'parent_id'], unique=False)
    op.create_index(op.f('ix_messages_user_id'), 'messages', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_user_id'), table_name='messages')
    op.drop_index('ix_messages_thread', table_name='messages')
    op.drop_index(op.f('ix_messages_record_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_parent_id'), table_name='messages')
    op.drop_index('ix_messages_model_record', table_name='messages')
    op.drop_index(op.f('ix_messages_model_name'), table_name='messages')
    op.drop_index(op.f('ix_messages_message_type'), table_name='messages')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_activity_logs_user_id'), table_name='activity_logs')
    op.drop_index('ix_activity_logs_user_action', table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_session_id'), table_name='activity_logs')
    op.drop_index('ix_activity_logs_security', table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_request_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_level'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_event_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_entity_type'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_entity_id'), table_name='activity_logs')
    op.drop_index('ix_activity_logs_entity', table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_created_at'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_correlation_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_company_id'), table_name='activity_logs')
    op.drop_index('ix_activity_logs_company_date', table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_category'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_action'), table_name='activity_logs')
    op.drop_table('activity_logs')
    # ### end Alembic commands ###
