"""add_messaging_configs

Revision ID: 70ed9e9a5e7d
Revises: 816ba7ebc8fd
Create Date: 2025-12-26 11:01:13.435841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70ed9e9a5e7d'
down_revision: Union[str, None] = '816ba7ebc8fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messaging_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('source_type', sa.Enum('USER', 'GROUP', 'ROLE', 'ALL', 'SAME_COMPANY', 'SAME_GROUP', name='messagingscope'), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('target_type', sa.Enum('USER', 'GROUP', 'ROLE', 'ALL', 'SAME_COMPANY', 'SAME_GROUP', name='messagingscope'), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('can_message', sa.Boolean(), nullable=False),
    sa.Column('can_see_online', sa.Boolean(), nullable=False),
    sa.Column('can_see_typing', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'source_type', 'source_id', 'target_type', 'target_id', name='uq_messaging_config_rule')
    )
    op.create_index(op.f('ix_messaging_configs_company_id'), 'messaging_configs', ['company_id'], unique=False)
    op.create_index(op.f('ix_messaging_configs_id'), 'messaging_configs', ['id'], unique=False)
    op.create_table('notification_preferences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('inbox_enabled', sa.Boolean(), nullable=False),
    sa.Column('inbox_sound', sa.Boolean(), nullable=False),
    sa.Column('inbox_desktop', sa.Boolean(), nullable=False),
    sa.Column('push_enabled', sa.Boolean(), nullable=False),
    sa.Column('push_messages', sa.Boolean(), nullable=False),
    sa.Column('push_mentions', sa.Boolean(), nullable=False),
    sa.Column('push_replies', sa.Boolean(), nullable=False),
    sa.Column('push_reactions', sa.Boolean(), nullable=False),
    sa.Column('push_activity', sa.Boolean(), nullable=False),
    sa.Column('email_enabled', sa.Boolean(), nullable=False),
    sa.Column('email_messages', sa.Boolean(), nullable=False),
    sa.Column('email_mentions', sa.Boolean(), nullable=False),
    sa.Column('email_digest', sa.Enum('NONE', 'IMMEDIATE', 'DAILY', 'WEEKLY', name='digestfrequency'), nullable=False),
    sa.Column('dnd_enabled', sa.Boolean(), nullable=False),
    sa.Column('dnd_start_time', sa.Time(), nullable=True),
    sa.Column('dnd_end_time', sa.Time(), nullable=True),
    sa.Column('dnd_weekends', sa.Boolean(), nullable=False),
    sa.Column('type_overrides', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_preferences_id'), 'notification_preferences', ['id'], unique=False)
    op.create_index(op.f('ix_notification_preferences_user_id'), 'notification_preferences', ['user_id'], unique=True)
    op.create_table('push_subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.String(length=500), nullable=False),
    sa.Column('p256dh_key', sa.String(length=500), nullable=False),
    sa.Column('auth_key', sa.String(length=500), nullable=False),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('device_name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint')
    )
    op.create_index(op.f('ix_push_subscriptions_id'), 'push_subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_push_subscriptions_is_active'), 'push_subscriptions', ['is_active'], unique=False)
    op.create_index('ix_push_subscriptions_user_active', 'push_subscriptions', ['user_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_push_subscriptions_user_id'), 'push_subscriptions', ['user_id'], unique=False)
    op.create_table('message_read_receipts',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id', 'user_id')
    )
    op.create_index('ix_read_receipts_message', 'message_read_receipts', ['message_id'], unique=False)
    op.create_index('ix_read_receipts_read_at', 'message_read_receipts', ['read_at'], unique=False)
    op.create_index('ix_read_receipts_user', 'message_read_receipts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_read_receipts_user', table_name='message_read_receipts')
    op.drop_index('ix_read_receipts_read_at', table_name='message_read_receipts')
    op.drop_index('ix_read_receipts_message', table_name='message_read_receipts')
    op.drop_table('message_read_receipts')
    op.drop_index(op.f('ix_push_subscriptions_user_id'), table_name='push_subscriptions')
    op.drop_index('ix_push_subscriptions_user_active', table_name='push_subscriptions')
    op.drop_index(op.f('ix_push_subscriptions_is_active'), table_name='push_subscriptions')
    op.drop_index(op.f('ix_push_subscriptions_id'), table_name='push_subscriptions')
    op.drop_table('push_subscriptions')
    op.drop_index(op.f('ix_notification_preferences_user_id'), table_name='notification_preferences')
    op.drop_index(op.f('ix_notification_preferences_id'), table_name='notification_preferences')
    op.drop_table('notification_preferences')
    op.drop_index(op.f('ix_messaging_configs_id'), table_name='messaging_configs')
    op.drop_index(op.f('ix_messaging_configs_company_id'), table_name='messaging_configs')
    op.drop_table('messaging_configs')
    # ### end Alembic commands ###
