"""add_attachments_table

Revision ID: 816ba7ebc8fd
Revises: 8b1bd3ab097a
Create Date: 2025-12-26 09:17:10.522934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '816ba7ebc8fd'
down_revision: Union[str, None] = '8b1bd3ab097a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=True),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('storage_backend', sa.String(length=20), nullable=False),
    sa.Column('attachable_type', sa.String(length=100), nullable=False),
    sa.Column('attachable_id', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('thumbnail_key', sa.String(length=500), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index('ix_attachments_attachable', 'attachments', ['attachable_type', 'attachable_id'], unique=False)
    op.create_index(op.f('ix_attachments_attachable_id'), 'attachments', ['attachable_id'], unique=False)
    op.create_index(op.f('ix_attachments_attachable_type'), 'attachments', ['attachable_type'], unique=False)
    op.create_index(op.f('ix_attachments_company_id'), 'attachments', ['company_id'], unique=False)
    op.create_index(op.f('ix_attachments_id'), 'attachments', ['id'], unique=False)
    op.create_index(op.f('ix_attachments_is_deleted'), 'attachments', ['is_deleted'], unique=False)
    op.create_index('ix_attachments_user_company', 'attachments', ['user_id', 'company_id'], unique=False)
    op.create_index(op.f('ix_attachments_user_id'), 'attachments', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attachments_user_id'), table_name='attachments')
    op.drop_index('ix_attachments_user_company', table_name='attachments')
    op.drop_index(op.f('ix_attachments_is_deleted'), table_name='attachments')
    op.drop_index(op.f('ix_attachments_id'), table_name='attachments')
    op.drop_index(op.f('ix_attachments_company_id'), table_name='attachments')
    op.drop_index(op.f('ix_attachments_attachable_type'), table_name='attachments')
    op.drop_index(op.f('ix_attachments_attachable_id'), table_name='attachments')
    op.drop_index('ix_attachments_attachable', table_name='attachments')
    op.drop_table('attachments')
    # ### end Alembic commands ###
