"""Add EnterpriseModel columns to User

Revision ID: 8c7109d77e0a
Revises: 6513586ffd9b
Create Date: 2025-12-25 23:32:30.655670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c7109d77e0a'
down_revision: Union[str, None] = '6513586ffd9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns with server_default for NOT NULL columns on existing data
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('deleted_by', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('metadata_json', sa.JSON(), nullable=False, server_default='{}'))
    op.add_column('users', sa.Column('tags', sa.JSON(), nullable=False, server_default='[]'))
    op.add_column('users', sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('deactivated_by', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('deactivation_reason', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('message_ids', sa.JSON(), nullable=False, server_default='[]'))
    op.add_column('users', sa.Column('follower_ids', sa.JSON(), nullable=False, server_default='[]'))
    op.add_column('users', sa.Column('version', sa.Integer(), nullable=False, server_default='1'))
    op.create_index(op.f('ix_users_is_deleted'), 'users', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_is_deleted'), table_name='users')
    op.drop_column('users', 'version')
    op.drop_column('users', 'follower_ids')
    op.drop_column('users', 'message_ids')
    op.drop_column('users', 'deactivation_reason')
    op.drop_column('users', 'deactivated_by')
    op.drop_column('users', 'deactivated_at')
    op.drop_column('users', 'tags')
    op.drop_column('users', 'metadata_json')
    op.drop_column('users', 'deleted_by')
    op.drop_column('users', 'deleted_at')
    op.drop_column('users', 'is_deleted')
    # ### end Alembic commands ###
