"""add_bookmarks_and_message_archive

Revision ID: ca184808e69a
Revises: 36a511a2fa73
Create Date: 2025-12-26 01:42:41.129067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca184808e69a'
down_revision: Union[str, None] = '36a511a2fa73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookmarks',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bookmark_type', sa.Enum('MESSAGE', 'NOTIFICATION', 'ACTIVITY', 'INBOX_ITEM', name='bookmarktype'), nullable=False),
    sa.Column('reference_id', sa.Integer(), nullable=False, comment='ID of the bookmarked item'),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookmarks_bookmark_type'), 'bookmarks', ['bookmark_type'], unique=False)
    op.create_index(op.f('ix_bookmarks_id'), 'bookmarks', ['id'], unique=False)
    op.create_index(op.f('ix_bookmarks_reference_id'), 'bookmarks', ['reference_id'], unique=False)
    op.create_index('ix_bookmarks_unique', 'bookmarks', ['user_id', 'bookmark_type', 'reference_id'], unique=True)
    op.create_index(op.f('ix_bookmarks_user_id'), 'bookmarks', ['user_id'], unique=False)
    op.create_index('ix_bookmarks_user_type', 'bookmarks', ['user_id', 'bookmark_type'], unique=False)
    # Add is_archived as nullable first, set default, then make NOT NULL
    op.add_column('messages', sa.Column('is_archived', sa.Boolean(), nullable=True))
    op.execute("UPDATE messages SET is_archived = FALSE WHERE is_archived IS NULL")
    op.alter_column('messages', 'is_archived', nullable=False, server_default=sa.text('false'))
    op.add_column('messages', sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('messages', sa.Column('archived_by', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_messages_is_archived'), 'messages', ['is_archived'], unique=False)
    op.create_foreign_key(None, 'messages', 'users', ['archived_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_index(op.f('ix_messages_is_archived'), table_name='messages')
    op.drop_column('messages', 'archived_by')
    op.drop_column('messages', 'archived_at')
    op.drop_column('messages', 'is_archived')
    op.drop_index('ix_bookmarks_user_type', table_name='bookmarks')
    op.drop_index(op.f('ix_bookmarks_user_id'), table_name='bookmarks')
    op.drop_index('ix_bookmarks_unique', table_name='bookmarks')
    op.drop_index(op.f('ix_bookmarks_reference_id'), table_name='bookmarks')
    op.drop_index(op.f('ix_bookmarks_id'), table_name='bookmarks')
    op.drop_index(op.f('ix_bookmarks_bookmark_type'), table_name='bookmarks')
    op.drop_table('bookmarks')
    # ### end Alembic commands ###
