"""Add RBAC models ContentType MenuItem UserMenuPermission AccessRule

Revision ID: e16d187435a7
Revises: 8c7109d77e0a
Create Date: 2025-12-26 00:22:06.698222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e16d187435a7'
down_revision: Union[str, None] = '8c7109d77e0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('app_label', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_label', 'model', name='uq_content_type_app_model')
    )
    op.create_index(op.f('ix_content_types_id'), 'content_types', ['id'], unique=False)
    op.create_table('menu_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=True),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('component', sa.String(length=500), nullable=True),
    sa.Column('redirect', sa.String(length=500), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('requires_auth', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['menu_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menu_items_code'), 'menu_items', ['code'], unique=True)
    op.create_index(op.f('ix_menu_items_id'), 'menu_items', ['id'], unique=False)
    op.create_table('user_menu_permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('menu_item_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('can_view', sa.Boolean(), nullable=True),
    sa.Column('can_edit', sa.Boolean(), nullable=True),
    sa.Column('can_delete', sa.Boolean(), nullable=True),
    sa.Column('can_create', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'menu_item_id', 'company_id', name='uq_user_menu_permission')
    )
    op.create_index(op.f('ix_user_menu_permissions_company_id'), 'user_menu_permissions', ['company_id'], unique=False)
    op.create_index(op.f('ix_user_menu_permissions_id'), 'user_menu_permissions', ['id'], unique=False)
    op.create_index(op.f('ix_user_menu_permissions_menu_item_id'), 'user_menu_permissions', ['menu_item_id'], unique=False)
    op.create_index(op.f('ix_user_menu_permissions_user_id'), 'user_menu_permissions', ['user_id'], unique=False)
    op.create_index('ix_user_menu_user_company', 'user_menu_permissions', ['user_id', 'company_id'], unique=False)
    op.create_table('access_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content_type_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('can_read', sa.Boolean(), nullable=True),
    sa.Column('can_write', sa.Boolean(), nullable=True),
    sa.Column('can_create', sa.Boolean(), nullable=True),
    sa.Column('can_delete', sa.Boolean(), nullable=True),
    sa.Column('domain_filter', sa.Text(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['content_type_id'], ['content_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_access_rule_content_type', 'access_rules', ['content_type_id'], unique=False)
    op.create_index('ix_access_rule_user_group', 'access_rules', ['user_id', 'group_id'], unique=False)
    op.create_index(op.f('ix_access_rules_company_id'), 'access_rules', ['company_id'], unique=False)
    op.create_index(op.f('ix_access_rules_content_type_id'), 'access_rules', ['content_type_id'], unique=False)
    op.create_index(op.f('ix_access_rules_group_id'), 'access_rules', ['group_id'], unique=False)
    op.create_index(op.f('ix_access_rules_id'), 'access_rules', ['id'], unique=False)
    op.create_index(op.f('ix_access_rules_user_id'), 'access_rules', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_access_rules_user_id'), table_name='access_rules')
    op.drop_index(op.f('ix_access_rules_id'), table_name='access_rules')
    op.drop_index(op.f('ix_access_rules_group_id'), table_name='access_rules')
    op.drop_index(op.f('ix_access_rules_content_type_id'), table_name='access_rules')
    op.drop_index(op.f('ix_access_rules_company_id'), table_name='access_rules')
    op.drop_index('ix_access_rule_user_group', table_name='access_rules')
    op.drop_index('ix_access_rule_content_type', table_name='access_rules')
    op.drop_table('access_rules')
    op.drop_index('ix_user_menu_user_company', table_name='user_menu_permissions')
    op.drop_index(op.f('ix_user_menu_permissions_user_id'), table_name='user_menu_permissions')
    op.drop_index(op.f('ix_user_menu_permissions_menu_item_id'), table_name='user_menu_permissions')
    op.drop_index(op.f('ix_user_menu_permissions_id'), table_name='user_menu_permissions')
    op.drop_index(op.f('ix_user_menu_permissions_company_id'), table_name='user_menu_permissions')
    op.drop_table('user_menu_permissions')
    op.drop_index(op.f('ix_menu_items_id'), table_name='menu_items')
    op.drop_index(op.f('ix_menu_items_code'), table_name='menu_items')
    op.drop_table('menu_items')
    op.drop_index(op.f('ix_content_types_id'), table_name='content_types')
    op.drop_table('content_types')
    # ### end Alembic commands ###
